# NUMPY

## Task 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [2]:
a = (np.array([
    [1, 2, 3, 3, 1],
    [6, 8, 11, 10, 7]
])).T

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis = 0)

In [5]:
mean_a

array([2. , 8.4])

## Task 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Task 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [9]:
a_centered_sp = np.dot(a_centered[0:, 0], a_centered[0:, 1])

In [10]:
a_centered_sp

8.0

In [11]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

# PANDAS

## Task 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [1]:
import numpy as np
import pandas as pd

In [2]:
authors = pd.DataFrame({'author_id':['1', '2', '3'],
                        'author_name':['Тургенев', 'Чехов', 'Островский']},
                        columns=['author_id', 'author_name']
                       )

In [3]:
authors

author_id author_name
0         1    Тургенев
1         2       Чехов
2         3  Островский

In [4]:
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                      'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                      'price': [450, 300, 350, 500, 450, 370, 290]})

In [5]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Task 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [8]:
authors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   author_id    3 non-null      object
 1   author_name  3 non-null      object
dtypes: object(2)
memory usage: 176.0+ bytes


In [9]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   author_id   7 non-null      int64 
 1   book_title  7 non-null      object
 2   price       7 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes


In [10]:
authors['author_id']=authors['author_id'].astype(int)

In [11]:
authors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   author_id    3 non-null      int32 
 1   author_name  3 non-null      object
dtypes: int32(1), object(1)
memory usage: 164.0+ bytes


In [12]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')

In [13]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Task 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [14]:
top5 = authors_price.nlargest(5, 'price')

In [15]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [16]:
top5 = top5.reset_index(drop=True)

In [17]:
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

## Task 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [18]:
authors_stat1 = authors_price.groupby('author_name').agg({'price':'max'})

In [19]:
authors_stat1 = authors_stat1.rename(columns = {'price':'max_price'})

In [20]:
authors_stat1

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [21]:
authors_stat2 = authors_price.groupby('author_name').agg({'price':'min'})

In [22]:
authors_stat2 = authors_stat2.rename(columns = {'price':'min_price'})

In [23]:
authors_stat2

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [24]:
authors_stat3 = authors_price.groupby('author_name').agg({'price':'mean'}).round(2)

In [25]:
authors_stat3 = authors_stat3.rename(columns = {'price':'mean_price'})

In [26]:
authors_stat3

mean_price
author_name            
Островский       330.00
Тургенев         366.67
Чехов            475.00

In [27]:
authors_stat = pd.concat([authors_stat1, authors_stat2, authors_stat3], axis=1)

In [28]:
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290      330.00
Тургенев           450        300      366.67
Чехов              500        450      475.00